# Generated by Django 4.2.1 on 2023-06-18 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('fname', models.CharField(max_length=50, verbose_name='First name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('town', models.CharField(max_length=20, verbose_name='Town')),
                ('joined_at', models.DateField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff_status')),
                ('phone', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(blank=True, default='default-profile-pic.jpeg', null=True, upload_to='profile_photos/', verbose_name='Profile photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('bio', models.CharField(default='No Bio ', max_length=200)),
                ('is_seller', models.BooleanField(default=True)),
                ('seller_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(blank=True, max_length=50)),
                ('admin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountVerificationPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True, null=True)),
                ('IDnumber', models.CharField(default='0000000000', max_length=20)),
                ('photo1', models.ImageField(upload_to='kyc_verification_photos/')),
                ('photo2', models.ImageField(upload_to='kyc_verification_photos/')),
                ('photo3', models.ImageField(upload_to='kyc_verification_photos/')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('seller_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_mgmt.customadmin')),
            ],
        ),
    ]
